### ISSUE TITLE
Support hybrid S3 datstorage

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/dat-share#4]
Support a DAT storage that still uses a local .dat, but reads the actual contents from S3.
Enable if S3_ROOT is set.
For example, ROOT_DIR and S3_ROOT are set, read .dat from `ROOT_DIR/<path>/.dat` and load contents from `S3_ROOT/<path>/`

Maybe can wrap a standard dat-storage with something like:

```
var local_dat_storage = DatStorage()

DatStorage(function(filename) {
   if (filename.startsWith(".dat/metadata") {
      return local_dat_storage.metadata(filename.substring(".dat/metadata".length);
   }

   if (filename.startsWith(".dat/content") {
      return local_dat_storage.content(filename.substring(".dat/content".length);
   }

   // actual file, load from s3
   return...
}
```

**Comment by N0taN3rd** [comment]
closed via 0b1e9664031d401464926f992deaf42592ec1152
